/**
 * GET /api/delivery/mock/guides/[slug] — the MOCK setup-guide PDF.
 *
 * A real setup guide is a purchased asset in PRIVATE storage behind a signed
 * URL; it must never be a public file. For the demo we generate a valid,
 * minimal PDF on the fly so the download button genuinely works, and say so on
 * the first page. Replace this whole route with signed private storage in
 * production.
 */
import { productRepository } from "@/lib/repositories";

type Ctx = { params: Promise<{ slug: string }> };

/** Escapes a string for a PDF literal and truncates to the line budget. */
function pdfLine(text: string, max = 92): string {
  return text
    .normalize("NFKD")
    // eslint-disable-next-line no-control-regex
    .replace(/[^\x20-\x7E]/g, "-")
    .slice(0, max);
}

function buildPdf(title: string, lines: string[]): Buffer {
  const content = [
    "BT",
    "/F1 16 Tf",
    "1 0 0 1 60 780 Tm",
    `(${pdfLine(title)}) Tj`,
    "/F1 10 Tf",
    ...lines.flatMap((line) => ["0 -18 Td", `(${pdfLine(line)}) Tj`]),
    "ET",
  ].join("\n");

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " +
      "/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}

export async function GET(_request: Request, context: Ctx) {
  const { slug } = await context.params;
  const product = await productRepository.getBySlug(slug);

  if (!product) {
    return new Response("Guide not found", { status: 404 });
  }

  const pdf = buildPdf(`Setup Guide - ${product.name}`, [
    "BLANC WEDDINGS - MOCK SETUP GUIDE (demo document).",
    "",
    "1. Open your purchase access page and choose Open Template.",
    "2. Canva creates your own editable copy of the template.",
    "3. Replace the names, dates, locations, wording and photographs.",
    "4. Publish your website from Canva.",
    "5. Share the published link with your guests.",
    "",
    `Included sections: ${product.includedSections.slice(0, 6).join(", ")}`,
    "",
    "This file is generated by the demo app. In production the real guide is",
    "stored privately and served through a short-lived signed URL.",
  ]);

  return new Response(new Uint8Array(pdf), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="blanc-${product.slug}-setup-guide.pdf"`,
      "Cache-Control": "no-store, private",
    },
  });
}
